# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 301, 200))
        self.tabWidget.setStyleSheet("border-style: solid;\n"
"border-width: 1.5px;\n"
"border-color: rgb(255, 0, 255);\n"
"background-color: rgb(32, 32, 32);\n"
"color: black;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 0, 295, 174))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("")
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 294, 175))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("color: white;")
        self.tab_3.setObjectName("tab_3")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 295, 174))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("")
        self.tab_4.setObjectName("tab_4")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 295, 174))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_4, "")
        self.PdfList = QtWidgets.QListWidget(self.centralwidget)
        self.PdfList.setGeometry(QtCore.QRect(520, 20, 256, 231))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PdfList.setFont(font)
        self.PdfList.setStyleSheet("border-style: solid;\n"
"border-width: 1.5px;\n"
"border-color: rgb(255, 0, 255);\n"
"background-color: rgb(32, 32, 32);")
        self.PdfList.setObjectName("PdfList")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.PdfList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.PdfList.addItem(item)
        self.OpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenButton.setGeometry(QtCore.QRect(520, 340, 81, 31))
        self.OpenButton.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 0, 255);\n"
"border-color: rgb(255, 0, 255);\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.OpenButton.setObjectName("OpenButton")
        self.DeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(630, 340, 141, 31))
        self.DeleteButton.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 0, 255);\n"
"border-color: rgb(255, 0, 255);\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.DeleteButton.setObjectName("DeleteButton")
        self.ScanButton = QtWidgets.QPushButton(self.centralwidget)
        self.ScanButton.setGeometry(QtCore.QRect(670, 500, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ScanButton.setFont(font)
        self.ScanButton.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 0, 255);\n"
"border-color: rgb(255, 0, 255);\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.ScanButton.setObjectName("ScanButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(520, 280, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 0, 255);\n"
"border-color: rgb(255, 0, 255);\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(680, 280, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 0, 255);\n"
"border-color: rgb(255, 0, 255);\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 280, 61, 21))
        self.label_4.setStyleSheet("color: rgb(255,0,255)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(620, 280, 61, 21))
        self.label_5.setStyleSheet("color: rgb(255, 0, 255)")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "How this Works!\n"
"\n"
"First, click on the \"open...\" button and select a .pdf File you would like to scan.\n"
"\n"
"(Page 1/4)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_2.setText(_translate("MainWindow", "How this Works!\n"
"\n"
"After you selected up to 3 PDFs, you can either scan all of them or scan a specific page on them, more about that on Tab 3&4\n"
"(Page 2/4)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label_3.setText(_translate("MainWindow", "How this Works!\n"
"\n"
"After you selected and scanned the PDFs, check the same folder this Program is in and open the generated .txt files. \n"
"(Page 3/4)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 3"))
        self.label_6.setText(_translate("MainWindow", "How this Works!\n"
"\n"
"If you want to scan one Page, enter the Page you want to scan into the \"Start Page\" and \"Last Page\" field. For Example, if you want to scan Page 5, enter \"5\" in the \'Start Page\' TextEdit and \'Last Page\' TextEdit\n"
"(Page 4/4)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 4"))
        __sortingEnabled = self.PdfList.isSortingEnabled()
        self.PdfList.setSortingEnabled(False)
        item = self.PdfList.item(0)
        item.setText(_translate("MainWindow", "Select up to 5 PDFs"))
        self.PdfList.setSortingEnabled(__sortingEnabled)
        self.OpenButton.setText(_translate("MainWindow", "Open..."))
        self.DeleteButton.setText(_translate("MainWindow", "Delete previous Entry"))
        self.ScanButton.setText(_translate("MainWindow", "Scan"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Start Page"))
        self.label_5.setText(_translate("MainWindow", "Last Page"))
